### PR TITLE
Fix failing bailout test

### PR DESCRIPTION
**Pull request by david-dot-krupicka**

### CODE REVIEW

**Comment by bleargh45** [comment]
David... I see your MR here, but am curious... what environment are you running it under, where you are seeing this output?

(as I have been unable to reproduce this output in any of the environments that I have tested under)

**Comment by bleargh45** [comment]
Pinging you back again to see if you can provide any further information on what environment where you are seeing the main branch fail (as I have been unable to reproduce).

**Comment by pghmcfc** [comment]
This PR fixes a failure to build in Fedora Rawhide, for example:
https://kojipkgs.fedoraproject.org/work/tasks/243/86020243/build.log
https://bugzilla.redhat.com/show_bug.cgi?id=2079320

**Comment by ppisar** [comment]
This is triggered by upgrading Test-Harness from 3.43 to 3.44.

**Comment by ppisar** [comment]
Bisected to this Test-Harness change:

~~~~
commit cb5f2b123f97a75dd787db0a06d1bd10fcfbf61c (HEAD, refs/bisect/bad)
Author: Dominik Sauer <dominik.sauer@gooddata.com>
Date:   Thu Jan 30 16:34:47 2020 +0100

    Let the aggregator finish gracefully after bailout
    
    Some derived harnesses, e.g. T:H:JUnit, do all their meaningful work
    (e.g. formatting aggregated test results into XML) after the
    aggregate_tests finishes normally. Bailing out prevented this
    meaningful work to be finished, causing the test results, including
    potential clues to why the test bailed out in first place, to be thrown
    away.
~~~~

**Comment by pghmcfc** [comment]
That came from https://github.com/Perl-Toolchain-Gang/Test-Harness/pull/96

Looks like `t/formatter.t` would need to special-case the bailout test in order to support T::H versions prior to 3.44 as well as later versions.

**Pull request merged**
